/*.$file${.::sensor.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: Sensor.qm
* File:  ${.::sensor.c}
*
* This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::sensor.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpn.h"    /* QP-nano framework API */
#include "bsp_ws.h"    /* Board Support Package interface */
#include "safe_std.h" /* portable "safe" <stdio.h>/<string.h> facilities */
#include <stdlib.h> /* for exit() */
Q_DEFINE_THIS_FILE

enum ADCSig{
ADC_SAMPLE_SIG = Q_USER_SIG,
};

//$declare(AOs::Sensor)
//$declare(AOs::Sensor_ctor)
static Sensor l_sensor;
QActive * const AO_Sensor = &l_sensor.super;

static void Sensor_ctor(void) {
    Sensor *me = (Sensor *)AO_Sensor;
    QActive_ctor(&me->super, Q_STATE_CAST(&Sensor_initial));
}

int main(){

static QEvt const *sensor_queueSto[10];
QF_init(Q_DIM(QF_active));
Sensor_ctor();
QACTIVE_START(AO_Sensor,
              1U,
              sensor_queueSto, Q_DIM(sensor_queueSto),
              (void*)0, 0U,
              (QEvt *)0);
return QF_run();
}
//$define(AOs::Sensor)
//$define(AOs::Sensor_ctor)

